apiVersion: v1
kind: Namespace
metadata:
  name: kasm
---
kind: Service
apiVersion: v1
metadata:
  name: kasm
  namespace: kasm
spec:
  type: ExternalName
  ports:
    - name: https-443  # Changed from https to https-443
      port: 443
      targetPort: 443
  externalName: 192.168.201.14
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kasm
  namespace: kasm
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.kasm.kbtech.org`)
      kind: Rule
      services:
        - name: kasm
          port: https-443  # Updated to use the new port name
    - match: Host(`kasm.kbtech.org`)
      kind: Rule
      services:
        - name: kasm
          port: https-443  # Updated to use the new port name
      middlewares:
        - name: default-headers
  tls:
    secretName: kbtech-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: kasm
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
