kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openspeedtest-claim
  namespace: openspeedtest-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi