# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: orbital-sync
#   namespace: orbital-sync
# spec:
#   selector:
#     app: orbital-sync
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080