apiVersion: v1
kind: Namespace
metadata:
  name: pfsensehome
---
apiVersion: v1
kind: Service
metadata:
  name: pfsensehome
  namespace: pfsensehome
spec:
  ports:
    - name: http
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pfsensehome
  namespace: pfsensehome
subsets:
  - addresses:
      - ip: 192.168.2.254   # pfSense IP
    ports:
      - name: http
        port: 443
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: pfsensehome
spec:
  headers:
    browserXSSFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: http
---
# If pfSense uses a self-signed cert, uncomment these and reference the serversTransport below
# apiVersion: traefik.io/v1alpha1
# kind: ServersTransport
# metadata:
#   name: pfsense-insecure
#   namespace: pfsensehome
# spec:
#   insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pfsensehome
  namespace: pfsensehome
  annotations:
    traefik.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.pfsensehome.kbtech.org`)
      kind: Rule
      services:
        - name: pfsensehome
          port: 443
          scheme: https
          # serversTransport: pfsense-insecure  # uncomment if using self-signed
      middlewares:
        - name: default-headers
    - match: Host(`pfsensehome.kbtech.org`)
      kind: Rule
      services:
        - name: pfsensehome
          port: 443
          scheme: https
          # serversTransport: pfsense-insecure  # uncomment if using self-signed
      middlewares:
        - name: default-headers
  tls:
    secretName: kbtech-tls
