kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: guacamole-claim
  namespace: guacamole-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi