apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole
  namespace: guacamole
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`guac.example.com`)   # <-- change to your FQDN
      kind: Rule
      services:
        - name: guacamole
          port: 8080
