apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: guacamole
spec:
  selector:
    app: guacd
  ports:
    - name: guacd
      port: 4822
      targetPort: 4822
---
apiVersion: v1
kind: Service
metadata:
  name: guac-mariadb
  namespace: guacamole
spec:
  selector:
    app: guac-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  # If you prefer a LoadBalancer instead of Ingress:
  # type: LoadBalancer
