apiVersion: v1
kind: Namespace
metadata:
  name: homepage-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage-server
data:
  # Minimal configs — expand later as you like
  settings.yaml: |
    title: KBTech Dashboard
    theme: dark
    layout:
      - Network
      - Tools
    quicklaunch:
      searchDescriptions: true
  services.yaml: |
    - Network:
        - pfSense:
            href: https://pfsensehome.kbtech.org
            icon: pfSense.png
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: true
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: long
  # Add more later if you want:
  # bookmarks.yaml: |
  #   - Homelab:
  #       - ChatGPT: https://chat.openai.com
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage-server
spec:
  selector:
    app: homepage
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage-server
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      # Homepage runs as root by default; that’s fine here. :contentReference[oaicite:1]{index=1}
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v0.9.12
          imagePullPolicy: IfNotPresent
          env:
            # REQUIRED: include your public host (comma-separated if multiple). :contentReference[oaicite:2]{index=2}
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.kbtech.org,www.homepage.kbtech.org
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config          # Homepage reads configs from here. :contentReference[oaicite:3]{index=3}
            - name: logs
              mountPath: /app/config/logs
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: homepage-config
          configMap:
            name: homepage-config
        - name: logs
          emptyDir: {}
---
# Traefik (CRD) exposure with your cert
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage-server
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`homepage.kbtech.org`) || Host(`www.homepage.kbtech.org`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: kbtech-tls   # must exist in the *homepage-server* namespace
