apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage-server
data:
  settings.yaml: |
    title: StarGate Command
    theme: dark
    background:
      image: /images/stargate.jpg   # served locally by the container
      blur: md
      brightness: 75
      opacity: 60
    layout:
      - Network
      - Infrastructure
      - Media
      - Cameras
      - Tools
    quicklaunch:
      searchDescriptions: true

  services.yaml: |
    - Network:
        - pfSense (HQ):
            href: https://pfsensehome.kbtech.org
            icon: pfsense
        - pfSense (NOC):
            href: https://pfsensenoc.kbtech.org
            icon: pfsense

    - Infrastructure:
        - Proxmox (HQ):
            href: https://proxmox.kbtech.org
            icon: proxmox
        - Proxmox (NOC):
            href: https://proxmox-noc.kbtech.org
            icon: proxmox
        - Proxmox (Moms):
            href: https://pvemoms.kbtech.org
            icon: proxmox
        - Unraid:
            href: https://unraid.kbtech.org
            icon: unraid
        - Tactical RMM:
            href: https://rmm.kbtech.org
            # Custom icon URL fallback in case there's no built-in slug:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/tacticalrmm.png

    - Media:
        - Sonarr:
            href: https://sonarr.kbtech.org
            icon: sonarr
        - Radarr:
            href: https://radarr.kbtech.org
            icon: radarr
        - Overseerr:
            href: https://request.kbtech.org
            icon: overseerr
        - Plex:
            href: https://app.plex.tv/desktop/#!/
            icon: plex

    - Smart Home:
        - Home Assistant:
            href: https://homeassistant.kbtech.org
            icon: home-assistant

    - Cameras:
        - Blue Iris:
            href: https://blue.kbtech.org
            icon: blue-iris

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: true
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: long
