apiVersion: v1
kind: Namespace
metadata:
  name: homepage-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage-server
data:
  # === REQUIRED so the app doesn't try to write it ===
  kubernetes.yaml: |
    mode: cluster        # use in-cluster ServiceAccount
    ingress: true        # discover k8s Ingress
    traefik: true        # discover Traefik IngressRoute (optional)

  settings.yaml: |
    title: StarGate Command
    theme: dark
    background:
      # Use any reliable hotlink-able image. Swap this to your Stargate ship art if you like.
      image: https://images.unsplash.com/photo-1447433819943-74a20887a81e?auto=format&fit=crop&w=2560&q=80
      blur: md
      brightness: 75
      opacity: 60
    layout:
      - Network
      - Infrastructure
      - Media
      - Home
      - Cameras
      - Tools
    quicklaunch:
      searchDescriptions: true

  services.yaml: |
    - Network:
        - pfSense (HQ):
            href: https://pfsensehome.kbtech.org
            icon: pfsense
            siteMonitor: https://pfsensehome.kbtech.org
        - pfSense (NOC):
            href: https://pfsensenoc.kbtech.org
            icon: pfsense
            siteMonitor: https://pfsensenoc.kbtech.org
        - Pi-hole 1:
            href: https://pihole1.kbtech.org
            icon: pi-hole
            siteMonitor: https://pihole1.kbtech.org/admin
        - Pi-hole 2:
            href: https://pihole2.kbtech.org
            icon: pi-hole
            siteMonitor: https://pihole2.kbtech.org/admin
        - Pi-hole 3:
            href: https://pihole3.kbtech.org
            icon: pi-hole
            siteMonitor: https://pihole3.kbtech.org/admin
        - Pi-hole 4:
            href: https://pihole4.kbtech.org
            icon: pi-hole
            siteMonitor: https://pihole4.kbtech.org/admin

    - Infrastructure:
        - Rancher:
            href: https://rancher.kbtech.org
            icon: rancher
            siteMonitor: https://rancher.kbtech.org
        - Proxmox (HQ):
            href: https://proxmox.kbtech.org
            icon: proxmox
            siteMonitor: https://proxmox.kbtech.org
        - Proxmox (NOC):
            href: https://proxmox-noc.kbtech.org
            icon: proxmox
            siteMonitor: https://proxmox-noc.kbtech.org
        - Proxmox (Moms):
            href: https://pvemoms.kbtech.org
            icon: proxmox
            siteMonitor: https://pvemoms.kbtech.org
        - Proxmox Backup Server:
            href: https://pbs-noc.kbtech.org
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox-backup-server.png
            siteMonitor: https://pbs-noc.kbtech.org
        - Proxmox Datacenter Manager:
            href: https://proxmox.kbtech.org/#v1:0:datacenter
            icon: proxmox
            siteMonitor: https://proxmox.kbtech.org
        - Unraid:
            href: https://unraid.kbtech.org
            icon: unraid
            siteMonitor: https://unraid.kbtech.org
        - Tactical RMM:
            href: https://rmm.kbtech.org
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/tacticalrmm.png
            siteMonitor: https://rmm.kbtech.org
        - UniFi:
            href: https://unifi.kbtech.org
            icon: unifi
            siteMonitor: https://unifi.kbtech.org
        - Kasm:
            href: https://kasm.kbtech.org
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/kasm.png
            siteMonitor: https://kasm.kbtech.org

    - Media:
        - Sonarr:
            href: https://sonarr.kbtech.org
            icon: sonarr
            siteMonitor: https://sonarr.kbtech.org
        - Radarr:
            href: https://radarr.kbtech.org
            icon: radarr
            siteMonitor: https://radarr.kbtech.org
        - Overseerr:
            href: https://request.kbtech.org
            icon: overseerr
            siteMonitor: https://request.kbtech.org

    - Home:
        - Home Assistant:
            href: https://homeassistant.kbtech.org
            icon: home-assistant
            siteMonitor: https://homeassistant.kbtech.org

    - Cameras:
        - Blue Iris:
            href: https://blue.kbtech.org
            icon: blue-iris
            siteMonitor: https://blue.kbtech.org

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: true
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true
          expanded: false
        namespace:
          name: homepage-server
          show: true
          expanded: false
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: long
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage-server
spec:
  selector:
    app: homepage
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage-server
  labels:
    app: homepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage   # <— important for kubernetes.yaml: mode: cluster
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.4.6
          imagePullPolicy: IfNotPresent
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.kbtech.org,www.homepage.kbtech.org
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits:   { cpu: 500m, memory: 512Mi }
      volumes:
        - name: homepage-config
          configMap:
            name: homepage-config
        - name: logs
          emptyDir: {}
---
# Read-only RBAC for Kubernetes + metrics + Traefik/Gateway discovery
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-readonly
rules:
  - apiGroups: [""]
    resources: [pods, services, endpoints, namespaces, nodes]
    verbs: [get, list, watch]
  - apiGroups: ["apps"]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list, watch]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses]
    verbs: [get, list, watch]
  - apiGroups: ["traefik.io"]
    resources: [ingressroutes]
    verbs: [get, list, watch]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: [httproutes, gateways]
    verbs: [get, list, watch]
  - apiGroups: ["metrics.k8s.io"]
    resources: [nodes, pods]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage-readonly
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage-server
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage-server
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`homepage.kbtech.org`) || Host(`www.homepage.kbtech.org`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: kbtech-tls
