---
apiVersion: v1
kind: Namespace
metadata:
  name: homarr-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr-server
  namespace: homarr-server
  labels:
    app: homarr-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homarr-server
  template:
    metadata:
      labels:
        app: homarr-server
    spec:
      nodeSelector:
        worker: "true"                # remove if not needed
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: fix-perms
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /mnt/icons /mnt/configs /mnt/data
              chown -R 1000:1000 /mnt
          volumeMounts:
            - name: homarr-content
              mountPath: /mnt/icons
              subPath: icons
            - name: homarr-content
              mountPath: /mnt/configs
              subPath: configs
            - name: homarr-content
              mountPath: /mnt/data
              subPath: data
      containers:
        - name: homarr-server
          image: ghcr.io/homarr-labs/homarr:0.15.2   # pin a version; avoid 'latest'
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Chicago
            - name: PORT
              value: "7575"
            - name: NEXTAUTH_URL
              value: https://homarr.kbtech.org
          ports:
            - name: http
              containerPort: 7575
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: homarr-content
              mountPath: /app/public/icons
              subPath: icons
            - name: homarr-content
              mountPath: /app/data/configs
              subPath: configs
            - name: homarr-content
              mountPath: /data
              subPath: data
      volumes:
        - name: homarr-content
          persistentVolumeClaim:
            claimName: homarr-claim
