---
apiVersion: v1
kind: Namespace
metadata:
  name: kasm
---
# Deploy Kasm via the official Helm chart using k3s' HelmChart CRD
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kasm
  namespace: kube-system
spec:
  chart: kasm-single-zone
  repo: https://kasmtech.github.io/kasm-helm
  # version: "1.17.0"   # <- optional: pin a chart version once you’re happy
  targetNamespace: kasm
  valuesContent: |
    # =========================
    # Global / core settings
    # =========================
    global:
      hostname: kasm.kbtech.org            # <-- EDIT to your DNS
      storageClassName: longhorn           # <-- EDIT (longhorn / your Ceph class)
      image:
        pullPolicy: IfNotPresent
      # Schedule all kasm pods on nodes with worker=true (matches your code-server pattern)
      nodeSelector:
        worker: "true"

    # =========================
    # Ingress (Traefik)
    # =========================
    ingress:
      enabled: true
      className: traefik-external          # your traefik class
      annotations:
        kubernetes.io/ingress.class: traefik-external
      tls:
        enabled: true
        # If you already have a wildcard/site cert in this secret, point to it:
        secretName: kbtech-tls             # <-- EDIT to your cert secret
      hosts:
        - host: kasm.kbtech.org            # <-- keep in sync with global.hostname
          paths:
            - path: /
              pathType: Prefix

    # =========================
    # Postgres persistence
    # =========================
    postgres:
      storage:
        size: 20Gi

    # =========================
    # Optional: set resources if you want
    # =========================
    # api:
    #   resources:
    #     requests: { cpu: "250m", memory: "512Mi" }
    #     limits:   { cpu: "1",    memory: "2Gi" }
    # manager:
    #   resources:
    #     requests: { cpu: "250m", memory: "512Mi" }
    #     limits:   { cpu: "1",    memory: "2Gi" }

    # Notes:
    # - This chart deploys core services (api, manager, guac, rdp-gateway, rdp-https-gateway, share).
    # - Agents still run on Proxmox VMs and register back to this Manager URL.
