kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-claim
  namespace: unifi
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi