apiVersion: v1
kind: Namespace
metadata:
  name: unifi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unifi
  name: unifi
  namespace: unifi
spec:
  selector:
    matchLabels:
      app: unifi
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi
    spec:
      nodeSelector:
        worker: "true"
      containers:
      - image: jacobalberty/unifi:latest
        imagePullPolicy: Always
        name: unifi
        volumeMounts:
        - mountPath: /data
          name: unifi-content

      volumes:
      - name: unifi-content
        persistentVolumeClaim:
          claimName: unifi-claim

